# Generated by Django 3.2.6 on 2022-01-25 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='آدرس دسته\u200cبندی')),
                ('status', models.BooleanField(default=True, verbose_name='آیا نشان داده شود؟')),
                ('position', models.IntegerField(verbose_name='پوزیشن')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childeren', to='hello.category', verbose_name='زیردسته')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی ها',
                'ordering': ['parent__id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thunbnail', models.ImageField(upload_to='images', verbose_name='لوگو')),
                ('title', models.CharField(max_length=200, verbose_name='نام تیم')),
                ('bazi', models.IntegerField(verbose_name='بازی')),
                ('bord', models.IntegerField(verbose_name='برد')),
                ('tasavi', models.IntegerField(verbose_name='تساوی')),
                ('bakht', models.IntegerField(verbose_name='باخت')),
                ('goalezade', models.IntegerField(verbose_name='گل زده')),
                ('goalekhorde', models.IntegerField(verbose_name='گل خورده')),
                ('tafazolegoal', models.IntegerField(verbose_name='تفاضل گل')),
                ('emtiaz', models.IntegerField(verbose_name='امتیاز')),
                ('rotbeh', models.IntegerField(verbose_name='رتبه در جدول')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='آدرس')),
                ('status', models.CharField(choices=[('d', 'پیش\u200cنویس'), ('p', 'منتشر شده')], max_length=1, verbose_name='وضعیت')),
                ('category', models.ManyToManyField(related_name='tables', to='hello.category', verbose_name='لیگ')),
            ],
            options={
                'verbose_name': 'جدول بازی',
                'verbose_name_plural': 'جدول\u200cهای بازی',
            },
        ),
        migrations.CreateModel(
            name='Rooznameh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام روزنامه')),
                ('thunbnail', models.ImageField(upload_to='images', verbose_name='لوگو')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='آدرس')),
                ('status', models.CharField(choices=[('d', 'پیش\u200cنویس'), ('p', 'منتشر شده')], max_length=1, verbose_name='وضعیت')),
                ('category', models.ManyToManyField(related_name='rooznam', to='hello.category', verbose_name='لیگ')),
            ],
            options={
                'verbose_name': 'روزنامه',
                'verbose_name_plural': 'روزنامه ها',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='منبع')),
                ('discriptions', models.TextField(verbose_name='متن')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='آدرس خبر')),
                ('status', models.CharField(choices=[('d', 'پیش\u200cنویس'), ('p', 'منتشر شده')], max_length=1, verbose_name='وضعیت')),
                ('category', models.ManyToManyField(related_name='news', to='hello.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'اخبار کوتاه',
                'verbose_name_plural': 'اخبار های کوتاه',
            },
        ),
        migrations.CreateModel(
            name='Natayej',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logomizban', models.ImageField(upload_to='images', verbose_name='لوگو ی میزبان')),
                ('logomihman', models.ImageField(upload_to='images', verbose_name='لوگو ی میهمان')),
                ('mizban', models.CharField(max_length=200, verbose_name='نام تیم میزبان')),
                ('mihman', models.CharField(max_length=200, verbose_name='نام تیم میهمان')),
                ('goalemizban', models.IntegerField(verbose_name='گل میزبان')),
                ('goalemihman', models.IntegerField(verbose_name='گل میهمان')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='آدرس')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('status', models.CharField(choices=[('d', 'پیش\u200cنویس'), ('p', 'منتشر شده')], max_length=1, verbose_name='وضعیت')),
                ('category', models.ManyToManyField(related_name='natayej', to='hello.category', verbose_name='لیگ')),
            ],
            options={
                'verbose_name': 'نتیجه بازی',
                'verbose_name_plural': 'نتیجه بازی ها',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='آدرس')),
                ('discriptions', models.TextField(verbose_name='محتوا')),
                ('thunbnail', models.ImageField(upload_to='images', verbose_name='تصویر')),
                ('alt', models.TextField(verbose_name='alt')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('status', models.CharField(choices=[('d', 'پیش\u200cنویس'), ('p', 'منتشر شده'), ('i', 'در حال بررسی'), ('b', 'برگشت داده شده')], max_length=1, verbose_name='وضعیت')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ManyToManyField(related_name='articles', to='hello.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-publish'],
            },
        ),
    ]
