# Generated by Django 3.2.6 on 2021-12-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20170801_0739'),
        ('comment', '0012_blockeduser_blockeduserhistory'),
    ]

    operations = [
    ]
